testGravity:
	clang++ -std=c++11 -Wall testGravity.cpp -o hell -lm -lsfml-graphics -lsfml-window -lsfml-system
simulation:
	clang++ -std=c++11 -Wall -pthread simulation.cpp -o simulate
visualisation:
	clang++ -std=c++11 -Wall visualisation.cpp -o visualize -lm -lsfml-graphics -lsfml-window -lsfml-system
clear:
	rm -f *.o
